name: projet_cours_MNIST
channels:
  - conda-forge
  - nodefaults
dependencies:
  - keras>=3.5.0, <4
  - tensorflow>=2.17.0, <3
  - numpy>=1.26.4, <2
  - pandas>=2.2.3, <3
  - matplotlib>=3.9.2, <4
  - ipykernel>=6.29.5, <7
  - jupyter>=1.1.1, <2
  - pydot>=3.0.1, <4
  - scikit-learn=1.5.2
  - seaborn>=0.13.2, <0.14
  - tqdm>=4.66.5, <5