[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MNIST"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"

[pypi-dependencies]
keras = ">=3.5.0, <4"
tensorflow = ">=2.17.0, <3"
numpy = ">=1.26.4, <2"
pandas = ">=2.2.3, <3"
matplotlib = ">=3.9.2, <4"
ipykernel = ">=6.29.5, <7"
jupyter = ">=1.1.1, <2"
pydot = ">=3.0.1, <4"
scikit-learn = ">=1.5.2, <2"
seaborn = ">=0.13.2, <0.14"
